# Generated by Django 5.2.3 on 2025-11-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_premium_customuser_premium_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('US', 'Estados Unidos'), ('CA', 'Canadá'), ('BR', 'Brasil'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Perú'), ('VE', 'Venezuela'), ('UY', 'Uruguay'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('EC', 'Ecuador'), ('CR', 'Costa Rica'), ('PA', 'Panamá'), ('DO', 'República Dominicana'), ('PR', 'Puerto Rico'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('SV', 'El Salvador'), ('NI', 'Nicaragua'), ('UK', 'Reino Unido'), ('IE', 'Irlanda'), ('FR', 'Francia'), ('DE', 'Alemania'), ('IT', 'Italia'), ('NL', 'Países Bajos'), ('BE', 'Bélgica'), ('LU', 'Luxemburgo'), ('CH', 'Suiza'), ('AT', 'Austria'), ('PL', 'Polonia'), ('CZ', 'República Checa'), ('HU', 'Hungría'), ('RO', 'Rumanía'), ('BG', 'Bulgaria'), ('SE', 'Suecia'), ('NO', 'Noruega'), ('DK', 'Dinamarca'), ('FI', 'Finlandia'), ('IS', 'Islandia'), ('PT', 'Portugal'), ('GR', 'Grecia'), ('TR', 'Turquía'), ('RU', 'Rusia'), ('UA', 'Ucrania'), ('EE', 'Estonia'), ('LV', 'Letonia'), ('LT', 'Lituania'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('HR', 'Croacia'), ('CN', 'China'), ('JP', 'Japón'), ('KR', 'Corea del Sur'), ('IN', 'India'), ('SG', 'Singapur'), ('MY', 'Malasia'), ('TH', 'Tailandia'), ('VN', 'Vietnam'), ('PH', 'Filipinas'), ('HK', 'Hong Kong'), ('ID', 'Indonesia'), ('AE', 'Emiratos Árabes Unidos'), ('SA', 'Arabia Saudita'), ('IL', 'Israel'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('KZ', 'Kazajistán'), ('ZA', 'Sudáfrica'), ('MA', 'Marruecos'), ('EG', 'Egipto'), ('NG', 'Nigeria'), ('KE', 'Kenia'), ('GH', 'Ghana'), ('DZ', 'Argelia'), ('TN', 'Túnez'), ('ET', 'Etiopía'), ('AU', 'Australia'), ('NZ', 'Nueva Zelanda')], default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
