# Generated by Django 5.2.3 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_remove_clase_precio_alter_reserva_estado'),
        ('users', '0011_customuser_country_customuser_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='premium_until',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='saldo_clases',
        ),
        migrations.AddField(
            model_name='customuser',
            name='clases_disponibles',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_saldo', to='clases.clase'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('ES', 'Spain'), ('IE', 'Ireland'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('LU', 'Luxembourg'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('IS', 'Iceland'), ('PT', 'Portugal'), ('GR', 'Greece'), ('TR', 'Turkey'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('EE', 'Estonia'), ('LV', 'Latvia'), ('LT', 'Lithuania'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('HR', 'Croatia'), ('US', 'United States'), ('CA', 'Canada'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Peru'), ('VE', 'Venezuela'), ('UY', 'Uruguay'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('EC', 'Ecuador'), ('CR', 'Costa Rica'), ('PA', 'Panama'), ('DO', 'Dominican Republic'), ('PR', 'Puerto Rico'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('SV', 'El Salvador'), ('NI', 'Nicaragua'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('IN', 'India'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('HK', 'Hong Kong'), ('ID', 'Indonesia'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('IL', 'Israel'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('KZ', 'Kazakhstan'), ('ZA', 'South Africa'), ('MA', 'Morocco'), ('EG', 'Egypt'), ('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('DZ', 'Algeria'), ('TN', 'Tunisia'), ('ET', 'Ethiopia'), ('AU', 'Australia'), ('NZ', 'New Zealand')], default='ES', max_length=2),
        ),
    ]
