# Generated by Django 5.2.3 on 2025-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clases_disponibles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='clases_disponibles_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('ES', 'Spain'), ('US', 'United States'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('UK', 'United Kingdom')], default='ES', max_length=2),
        ),
    ]
