# Generated by Django 5.2.3 on 2025-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_remove_clase_precio_alter_reserva_estado'),
        ('users', '0013_remove_customuser_clases_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clases_disponibles_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='clases_compradas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_compraron', to='clases.clase'),
        ),
    ]
