# Generated by Django 5.2.3 on 2025-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_clases_disponibles_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('CR', 'Costa Rica'), ('PA', 'Panama'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('SV', 'El Salvador'), ('NI', 'Nicaragua'), ('DO', 'Dominican Republic'), ('PR', 'Puerto Rico'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Peru'), ('VE', 'Venezuela'), ('UY', 'Uruguay'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('EC', 'Ecuador'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('IE', 'Ireland'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('LU', 'Luxembourg'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('PT', 'Portugal'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('IS', 'Iceland'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('EE', 'Estonia'), ('LV', 'Latvia'), ('LT', 'Lithuania'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('HR', 'Croatia'), ('GR', 'Greece'), ('TR', 'Turkey'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('HK', 'Hong Kong'), ('TW', 'Taiwan'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('ID', 'Indonesia'), ('IN', 'India'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('IL', 'Israel'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('KZ', 'Kazakhstan'), ('MA', 'Morocco'), ('EG', 'Egypt'), ('DZ', 'Algeria'), ('TN', 'Tunisia'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('AU', 'Australia'), ('NZ', 'New Zealand')], default='ES', max_length=2),
        ),
    ]
