# Generated by Django 5.2.3 on 2025-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clases_compradas',
        ),
        migrations.AddField(
            model_name='customuser',
            name='saldo_clases_50min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saldo_clases_90min',
            field=models.IntegerField(default=0),
        ),
    ]
