# Generated by Django 5.2.3 on 2025-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_clases_compradas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saldo_clases_30min',
            field=models.IntegerField(default=0),
        ),
    ]
