# Generated by Django 5.2.3 on 2025-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_saldo_clases_30min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_30min',
            new_name='saldo_clases_25min',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_90min',
            new_name='saldo_clases_80min',
        ),
    ]
