# Generated by Django 5.2.3 on 2025-12-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_saldo_clases_30min_customuser_saldo_clases_25min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_25min',
            new_name='saldo_clases_30min',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_80min',
            new_name='saldo_clases_90min',
        ),
    ]
