# Generated by Django 5.2.3 on 2025-12-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_saldo_clases_25min_customuser_saldo_clases_30min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_30min',
            new_name='saldo_clases_25min',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo_clases_90min',
            new_name='saldo_clases_80min',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
