# Generated by Django 5.2.3 on 2025-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(25, '25 minutos - 6€'), (50, '50 minutos - 12€'), (80, '80 minutos - 16€')]),
        ),
    ]
