# Generated by Django 5.2.3 on 2025-12-02 00:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_itemcarrito_duracion_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritocompra',
            options={'verbose_name': 'Carrito de Compra', 'verbose_name_plural': 'Carritos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-creada_en'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(25, '25 minutos'), (50, '50 minutos'), (80, '80 minutos')]),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL),
        ),
    ]
