# Generated by Django 5.2.3 on 2025-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='precio',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente (compra iniciada)'), ('aceptada', 'Aceptada por el profesor'), ('rechazada', 'Rechazada por el profesor'), ('completada', 'Clase completada'), ('validada', 'Validada por el profesor')], default='pendiente', max_length=20),
        ),
    ]
