# Generated by Django 5.2.3 on 2025-11-13 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_horariodisponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_recurrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios recurrentes',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('profesor', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioDisponible',
        ),
    ]
