# Generated by Django 5.2.3 on 2025-11-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_horariorecurrente_delete_horariodisponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-creada_en']},
        ),
    ]
