# Generated by Django 5.2.3 on 2025-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(50, '50 minutos'), (90, '1 hora y 30 minutos'), (30, '30 minutos')], default=50),
        ),
    ]
