# Generated by Django 5.2.3 on 2025-12-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_alter_clase_duracion_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='duracion_minutos',
            field=models.IntegerField(choices=[(25, '25 minutos'), (50, '50 minutos'), (80, '80 minutos')], default=50),
        ),
    ]
